version: "3.8"

services:
  web-client:
    build:
      context: ../../services/web-client
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - "../../services/web-client:/app"
    ports:
      - "3001:3001"

  socket:
    build:
      context: ../../services/socket
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - "../../services/socket:/app"
    ports:
      - "3000:3000"
