version: '3.0'

services:
  web-client:
    build:
      context: ../../services/web-client
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - socket
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=https://kurentochat-ak.staging.forasoft.com/socket.io/
    ports:
      - '3101:3001'

  socket:
    build:
      context: ../../services/socket
      environment:
        - ALLOWED_ORIGIN=https://kurentochat-ak.staging.forasoft.com
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3100:3000'
