version: "3.8"

services:
  web-client:
    build:
      context: ../../services/web-client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3101:3001"

  socket:
    build:
      context: ../../services/socket
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "../../services/socket:/app"
    ports:
      - "3100:3000"
